[project]
name = "piston_rspy"
version = "0.3.0"
description = "Python bindings for piston_rs."
readme = "README.md"
documentation = "https://jonxslays.github.io/piston_rspy/piston_rspy/"
repository = "https://github.com/Jonxslays/piston_rspy"
url = "https://github.com/Jonxslays/piston_rspy"
requires-python = ">=3.7,<3.11"

[tool.pyright]
typeCheckingMode = "strict"
include = ["piston_rspy"]

[tool.black]
line-length = 99

[build-system]
# requires = ["maturin>=0.12,<0.13"]
# build-backend = "maturin"
requires = ["setuptools", "wheel", "setuptools-rust"]
